language: java
jdk: oraclejdk8
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: deployment
    skip_cleanup: true
    on: &2
      branch: master
    bucket: telegram-bots-delivery-bucket
    region: eu-central-1b
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: telegram-bots-delivery-bucket
    key: telegram-bots.jar
    application: telegram-bots-deploy
    deployment_group: bots
    region: eu-central-1b
    on: *2
script:
  - ./gradlew shadowJar
  - mkdir -p deployment
  - mv build/libs/telegram-bots.jar deployments/